import {Pipe, PipeTransform, inject} from '@angular/core';
import {DomSanitizer, SafeHtml} from '@angular/platform-browser';
import {CHARACTERS, Character} from '../data/characters.data';

/** SVG markup is exclusively generated by the local roster, never supplied by a user or a remote page. */
@Pipe({name: 'characterPortrait'})
export class CharacterPortraitPipe implements PipeTransform {
  private readonly sanitizer = inject(DomSanitizer);
  transform(character: Character): SafeHtml | string {
    if (!CHARACTERS.includes(character)) return '';
    return this.sanitizer.bypassSecurityTrustHtml(character.silhouetteSvg);
  }
}
